### ISSUE TITLE
What kinds of contributions are you looking for?

### ISSUE THREAD

**Issue by cndofx** [TiagoRCorreia/rtodo#1]
I'm interested in doing something but I'd like more clarification on what you want first. 
I see opportunities for small things like simple cleanup and refactoring, but also some larger changes like implementing better error handling with crates like `thiserror` and/or `anyhow`, or cleaner user input with `rustyline`.
I also see your milestones for persistent storage and command line arguments, are those things you want to implement yourself or would PRs be welcome there too?

note: I'm pretty new to open source contributions like these, but I am pretty familiar with rust so this seems like a good opportunity for me to learn something too.
Thanks!

**Comment by TiagoRCorreia** [comment]
Hello, welcome.
I'm new at programming and rust. So, things like refactoring and cleanup will be cool.  Larger changes will be cool too for learning new crates and how implemented them. So, feel free to do what you want more.  
I will work in persistence storage, I'm thinking of using the **json** format, what  do you think?

Thanks!!!

Note: Sorry about my English!!!

**Comment by cndofx** [comment]
Cool, I'll see what I can do when I have time

> I will work in persistence storage, I'm thinking of using the **json** format, what do you think?

Nothing wrong with that. The `serde` and `serde_json` crates together should make that pretty easy to do.

**Comment by TiagoRCorreia** [comment]
I'm working on it with serde.
